all:
  children:
    rabbitmq_nodes:
      hosts:
        rabbitmq-node-01:
          ansible_host: 192.168.1.10
          ansible_user: ubuntu
        rabbitmq-node-02:
          ansible_host: 192.168.1.11
          ansible_user: ubuntu
        rabbitmq-node-03:
          ansible_host: 192.168.1.12
          ansible_user: ubuntu
      vars:
        ansible_python_interpreter: /usr/bin/python3
